Public Class SRAlarmCode
    Public Const IsOK As String = "OK"
    Public Const IsDoorOpen As String = "目前門開啟，請檢查訊號"
    Public Const IsNotLoadRecipe As String = "未載入 Recipe"
    Public Const IsStop As String = "程式已暫停"
    Public Const IsPowerOff As String = "電源已關閉"
    Public Const IsTimeOut As String = "已超時，請檢查訊號"
    Public Const IsFailed As String = "失敗，請檢查硬體"
    Public Const IsInitialFailed As String = "初始化失敗"
    Public Const IsCanNotInitial As String = "無法初始化，請檢查系統狀態"
    Public Const IsNotDefine As String = "未定義錯誤"
    Public Const IsHardwareError As String = "硬體錯誤"
    Public Const IsInspectError As String = "檢測錯誤"
    Public Const IsCanNotInspect As String = "不能檢測，請檢查系統狀態"
    Public Const IsDataBaseReadFailed As String = "資料庫讀取失敗，請檢資料庫"
    Public Const IsRecipeIDNotNumber As String = "Recipe ID 含有非數字字元"
    Public Const IsThreadCreateFailed As String = "流程開啟失敗"
    Public Const IsNotProductInformation As String = "無產品之資訊，請先下載產品資訊"
    Public Const IsNotSafty As String = "汽缸干涉，橫移馬達進入"
    Public Const IsUpdateModelFailed As String = "更新樣本失敗"
    Public Const IsAllocateInspectFailed As String = "初始化檢測失敗"

    Public Const IsLightMoveUpTimeout As String = "燈源移動至上位超時"
    Public Const IsLightMoveDownTimeout As String = "燈源移動至下位超時"
    Public Const IsLightMoveUpFailed As String = "燈源移動至上位失敗"
    Public Const IsLightMoveDownFailed As String = "燈源移動至下位失敗"

    Public Const IsChangeExposureTimeFailed As String = "設定曝光時間失敗"
    Public Const IsSnapFailed As String = "取像失敗"
    Public Const IsNotSafe As String = "動作失敗，非安全"
    Public Const IsLocateFailed As String = "定位失敗"
    Public Const IsChangeModelFailed As String = "更換樣本失敗"
    Public Const IsReadCodeFailed As String = "讀取條碼失敗"
    Public Const IsUpdateImageFailed As String = "更新影像失敗"
    Public Const IsCodeReaderUpdateImageFailed As String = "更新條碼影像失敗"
    Public Const IsCodeReaderParameterFailed As String = "條碼參數錯誤，請檢查條碼參數"

    Public Const IsSetRecipeIDFailed As String = "設定 PLC Recipe ID 失敗"

    Public Const IsHandshakeReadFailed As String = "TCP 讀取資訊失敗"
    Public Const IsSendLotInfoACKFailed As String = "TCP 發送產品資訊回應失敗"
    Public Const IsSendStripMapDownloadACKFailed As String = "TCP 發送下載產品分布回應失敗"
    Public Const IsSendStripMapUploadFailed As String = "TCP 發送上傳產品分布失敗"
    Public Const IsReadStripMapUploadACKFailed As String = "TCP 讀取上傳產品分布回應失敗"
    Public Const IsChangeRecipeFailed As String = "更換 Recipe 失敗"
    Public Const IsRecipeImageIsNothing As String = "無 Recipe 影像"
    Public Const IsUpdateRecipeModelFailed As String = "更新 Recipe 樣本失敗"
    Public Const IsWaitHandshakeTimeout As String = "TCP 等待交握超時"
    Public Const IsChangeCameraExposureTimeFailed As String = "設定檢測相機曝光時間失敗"
    Public Const IsChangeCodeReaderCameraExposureTimeFailed As String = "設定條碼相機曝光時間失敗"
    Public Const IsSendUpdateAIInfoFailed As String = "TCP 發送上傳AI資訊失敗"

    Public Const IsHandshakeNotConnected As String = "手臂通訊無連線"
    Public Const IsHandshakeFailed As String = "手臂通訊失敗"
End Class